apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nota-front
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sebastianjordan19/nota-front  # cambia por tu repo
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
